#version 450



layout (local_size_x = 16, local_size_y = 16) in;

layout(rgba8,set = 0, binding = 0) uniform image2D image;

void main() 
{
	vec4 value = vec4(0.0, 0.0, 0.0, 1.0);
    ivec2 texelCoord = ivec2(gl_GlobalInvocationID.xy);
	ivec2 size = imageSize(image);
    if(texelCoord.x < size.x && texelCoord.y < size.y)
    {

        value.x = float(texelCoord.x)/(size.x);
        value.y = float(texelCoord.y)/(size.y);	
    
        imageStore(image, texelCoord, value);
    }

   
}

